[PDI-16671]-"Something Went Wrong" error message shows up when trying to Inspect Data which has a field name with Double Quotes.
pentaho/pdi-dataservice-plugin pull request #142
Opened 2018-02-05 10:07 UTC by denisprotopopov

- additional fix. for pivot table

2018-02-05 10:20 UTC, wingman-pentaho commented
### Build Completed

:x: This pull request has errors. They will need to be addressed before it can be accepted. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -Dsurefire.runOrder=alphabetical -B -fn -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd clean install && mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd site
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLCondition.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLField.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/core/jdbc/ThinUtilTest.java
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: <0.1%</b> (click to expand)</summary>

###### org.pentaho.di.core.jdbc.ThinUtil
 * Branch Change: **-0.8%** :small_red_triangle_down:
 * Complexity Change: **-1.2%** :small_red_triangle_down:

###### org.pentaho.di.core.sql.SQLField
 * Complexity Change: **-0.7%** :small_red_triangle_down:
 * Instruction Change: **-1.9%** :small_red_triangle_down:
 * Line Change: **-1.6%** :small_red_triangle_down:
 * Method Change: **-2.9%** :small_red_triangle_down:

</details>

#### Checkstyle violations

The code submitted is not complying with one or more of our guidelines. To perform these checks locally, [please use this tool](https://github.com/pentaho/pentaho-coding-standards).

###### /home/buildguy/project/pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java

> :heavy_exclamation_mark: '(' is not followed by whitespace. at Line: 685 Column: 14

> :heavy_exclamation_mark: '(' is not followed by whitespace. at Line: 685 Column: 21

> :heavy_exclamation_mark: ')' is not preceded with whitespace. at Line: 685 Column: 26

> :heavy_exclamation_mark: ')' is not preceded with whitespace. at Line: 685 Column: 27

2018-02-05 10:30 UTC, wingman-pentaho commented
### Build Completed

:fire: This pull request has some issues. It would be preferable to fix them in order for it to be just perfect. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -Dsurefire.runOrder=alphabetical -B -fn -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd clean install && mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd site
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLCondition.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLField.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/core/jdbc/ThinUtilTest.java
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: <0.1%</b> (click to expand)</summary>

###### org.pentaho.di.core.jdbc.ThinUtil
 * Branch Change: **-0.8%** :small_red_triangle_down:
 * Complexity Change: **-1.2%** :small_red_triangle_down:

###### org.pentaho.di.core.sql.SQLField
 * Complexity Change: **-0.7%** :small_red_triangle_down:
 * Instruction Change: **-1.9%** :small_red_triangle_down:
 * Line Change: **-1.6%** :small_red_triangle_down:
 * Method Change: **-2.9%** :small_red_triangle_down:

</details>

2018-02-06 08:00 UTC, denisprotopopov commented
@pamval @mbatchelor please review the changes

2018-02-08 08:46 UTC, denisprotopopov commented
@bmorrise  @pamval @mbatchelor please review the changes

2018-02-12 14:15 UTC, denisprotopopov commented
@bmorrise @pamval @mbatchelor please review the changes

2018-02-12 16:43 UTC, marcbatchelor-nucleus requested changes

2018-02-12 16:43 UTC, mbatchelor commented on pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
> +    if ( builder.indexOf( "\"\"" ) > 0 &&  builder.length() > 0 && builder.charAt( 0 ) == '"'
Please replace this with:
    if ( str.startsWith("\"") && str.endsWith("\"")) {
      return str.substring(1, str.length() - 1 );
    } else {
      return str;
    }

Performance will be much better than using indexof and creating an intermediate object.

2018-02-12 16:43 UTC, mbatchelor commented on pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
> +  public static String replaceSubString( String strSrc, String strA, String replacement ) {
So why do this when String has a replaceAll method that accepts a regular expression ?
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll(java.lang.String,%20java.lang.String)

2018-02-13 06:40 UTC, wingman-pentaho commented
### Build Completed

:x: This pull request has errors. They will need to be addressed before it can be accepted. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -Dsurefire.runOrder=alphabetical -B -fn -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd clean install && mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd site
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLCondition.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLField.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/core/jdbc/ThinUtilTest.java
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: <0.1%</b> (click to expand)</summary>

###### org.pentaho.di.core.jdbc.ThinUtil
 * Branch Change: **-0.7%** :small_red_triangle_down:
 * Complexity Change: **-1.1%** :small_red_triangle_down:

###### org.pentaho.di.core.sql.SQLField
 * Complexity Change: **-0.7%** :small_red_triangle_down:
 * Instruction Change: **-1.9%** :small_red_triangle_down:
 * Line Change: **-1.6%** :small_red_triangle_down:
 * Method Change: **-2.9%** :small_red_triangle_down:

</details>

#### Checkstyle violations

The code submitted is not complying with one or more of our guidelines. To perform these checks locally, [please use this tool](https://github.com/pentaho/pentaho-coding-standards).

###### /home/buildguy/project/pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java

> :heavy_exclamation_mark: '(' is not followed by whitespace. at Line: 664 Column: 28

2018-02-13 08:01 UTC, wingman-pentaho commented
### Build Completed

:fire: This pull request has some issues. It would be preferable to fix them in order for it to be just perfect. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -Dsurefire.runOrder=alphabetical -B -fn -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd clean install && mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd site
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/jdbc/ThinUtil.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLCondition.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQLField.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/core/jdbc/ThinUtilTest.java
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: <0.1%</b> (click to expand)</summary>

###### org.pentaho.di.core.jdbc.ThinUtil
 * Branch Change: **-0.7%** :small_red_triangle_down:
 * Complexity Change: **-1.1%** :small_red_triangle_down:

###### org.pentaho.di.core.sql.SQLField
 * Complexity Change: **-0.7%** :small_red_triangle_down:
 * Instruction Change: **-1.9%** :small_red_triangle_down:
 * Line Change: **-1.6%** :small_red_triangle_down:
 * Method Change: **-2.9%** :small_red_triangle_down:

</details>

2018-02-14 06:29 UTC, denisprotopopov commented
@mbatchelor please review the changes.

2018-02-15 10:09 UTC, denisprotopopov commented
@mbatchelor please review the changes.

2018-02-19 08:10 UTC, denisprotopopov commented
@bmorrise @pamval @mbatchelor please review the changes

2018-02-21 07:37 UTC, denisprotopopov commented
@bmorrise @pamval @mbatchelor please review the changes

2018-02-26 06:52 UTC, denisprotopopov commented
@bmorrise @pamval @mbatchelor please review the changes

2018-02-26 14:31 UTC, merged