[PDI-17758] - Thread Deadlock using data services data source from sp…
pentaho/pdi-dataservice-plugin pull request #174
Opened 2019-02-11 13:51 UTC by bantonio82

…oon, also hammering the server

@pentaho/tatooine @pentaho/kashyyyk

2019-02-11 14:00 UTC, wingman-pentaho commented
### Build Completed

:x: This pull request has errors. They will need to be addressed before it can be accepted. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -Dsurefire.runOrder=alphabetical -Daudit -amd clean install
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQL.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinDatabaseMetaData.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java
  pdi-dataservice-client/src/test/resources/jdbc/emptyListServices.xml
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: +0.3%</b> (click to expand)</summary>

###### org.pentaho.di.trans.dataservice.jdbc.ThinDatabaseMetaData
 * Branch Change: **-0.8%** :small_red_triangle_down:
 * Complexity Change: **-0.4%** :small_red_triangle_down:
 * Instruction Change: **-0.7%** :small_red_triangle_down:
 * Line Change: **-0.2%** :small_red_triangle_down:

</details>

#### License header violations

> :heavy_exclamation_mark: Copyright year is not the current year on pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQL.java. Found 2018. Was expecting 2019

> :heavy_exclamation_mark: Copyright year is not the current year on pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java. Found 2018. Was expecting 2019

2019-02-11 15:12 UTC, JoaoRMF requested changes
Review also, the license headers

2019-02-11 15:12 UTC, JoaoRMF commented on pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
> +        serviceArguments.append( serviceName );
Do a URL encoding of this value. The service name can, for example, have spaces and/or special characters.

2019-02-11 15:18 UTC, JoaoRMF commented on pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
> +      StringBuilder serviceArguments = new StringBuilder().append( "/listServices" );
Where is this new parameter read? I think I'm missing the PR for this part?

2019-02-11 17:39 UTC, wingman-pentaho commented
### Build Completed

:fire: This pull request has some issues. It would be preferable to fix them in order for it to be just perfect. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -Dsurefire.runOrder=alphabetical -Daudit -amd clean install
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQL.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinDatabaseMetaData.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java
  pdi-dataservice-client/src/test/resources/jdbc/emptyListServices.xml
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: +0.3%</b> (click to expand)</summary>

###### org.pentaho.di.trans.dataservice.jdbc.ThinDatabaseMetaData
 * Branch Change: **-0.8%** :small_red_triangle_down:
 * Complexity Change: **-0.4%** :small_red_triangle_down:
 * Instruction Change: **-0.7%** :small_red_triangle_down:
 * Line Change: **-0.2%** :small_red_triangle_down:

</details>

2019-02-11 17:43 UTC, JoaoRMF requested changes

2019-02-11 17:43 UTC, JoaoRMF commented on pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java
> +  public void testgetServiceNames() throws Exception {
Camel case method name is missing

2019-02-11 17:59 UTC, wingman-pentaho commented
### Build Completed

:fire: This pull request has some issues. It would be preferable to fix them in order for it to be just perfect. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -Dsurefire.runOrder=alphabetical -Daudit -amd clean install
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQL.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinDatabaseMetaData.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java
  pdi-dataservice-client/src/test/resources/jdbc/emptyListServices.xml
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: +0.3%</b> (click to expand)</summary>

###### org.pentaho.di.trans.dataservice.jdbc.ThinDatabaseMetaData
 * Branch Change: **-0.8%** :small_red_triangle_down:
 * Complexity Change: **-0.4%** :small_red_triangle_down:
 * Instruction Change: **-0.7%** :small_red_triangle_down:
 * Line Change: **-0.2%** :small_red_triangle_down:

</details>

2019-02-12 14:15 UTC, JoaoRMF approved these changes

2019-02-12 14:19 UTC, wingman-pentaho commented
### Build Completed

:fire: This pull request has some issues. It would be preferable to fix them in order for it to be just perfect. See below for more details. Some links are also available below for further assistance in addressing those issues.

#### Build Commands

```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -Dsurefire.runOrder=alphabetical -Daudit -amd clean install
```

#### Cleanup Commands
```sh
mvn -B -f 'pom.xml' -pl 'pdi-dataservice-client' -P '!assemblies' -amd build-helper:remove-project-artifact
```

#### Changed files

```console
  pdi-dataservice-client/src/main/java/org/pentaho/di/core/sql/SQL.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClient.java
  pdi-dataservice-client/src/main/java/org/pentaho/di/trans/dataservice/jdbc/ThinDatabaseMetaData.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/RemoteClientTest.java
  pdi-dataservice-client/src/test/java/org/pentaho/di/trans/dataservice/jdbc/ThinDatabaseMetaDataTest.java
  pdi-dataservice-client/src/test/resources/jdbc/emptyListServices.xml
```

#### Unit Test Coverage

These statistics help you identify how your changes have affected the coverage of the following files. If a file is not in this list, then its coverage was not affected by your changes. To get some help interpreting these metrics, please refer to [Jacoco's documentation](http://eclemma.org/jacoco/trunk/doc/counters.html).

<details>
<summary>:warning: <b>Coverage Changes: +0.4%</b> (click to expand)</summary>

###### org.pentaho.di.trans.dataservice.jdbc.ThinDatabaseMetaData
 * Instruction Change: **-0.5%** :small_red_triangle_down:
 * Line Change: **-0.2%** :small_red_triangle_down:

</details>

2019-02-12 16:16 UTC, sailingscally approved these changes

2019-02-12 16:16 UTC, merged